#!/bin/zsh
#binded to F in library view

file="$(cmus-remote -C 'echo {}')"
album="$(beet ls -f '$album' $file)"

if ! [[ "$file" =~ .*/Favorites/.* ]]; then
	cmus-remote -C "echo '$album' already marked as not favorite"
else	
	beet modify -a $album favorite=0 -y
	cmus-remote -C "echo '$album' marked as not favorite"
	cmus-update-library	
fi
