#!/bin/zsh

convert_file_to_mp3() {

    file=$1
    name="$(echo $file | rev | cut -d '.' -f 2- | rev )"
    ffmpeg -i $file "$name.mp3" && rm $file

}

input="$(tree -if -I '*.mp3' $1)"
files=( ${(ps/\n/)input} )
for i in tr '\n' $files
    do
    [[ -f $i ]] && convert_file_to_mp3 $i
 done


