#global options
directory: /home/leonardo/music/Library
library: /home/leonardo/music/Library/Library.db

original_date: yes
format_item: $artist - $album - $title
format_album: $albumartist - date $album
per_disc_numbering: yes
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '[:]': ' -'

#import config
import:
  move: yes
  resume: ask
  languages: en es
  set_fields:
    favorite: 0
  log: ~/.config/beets/importLog.txt


#Plugins config
plugins: fromfilename acousticbrainz fetchart embedart importadded zero inline replaygain info edit missing follow lyrics smartplaylist playlist mbsync 
acousticbrainz:
  tags: average_loudness bpm danceable mood_acoustic mood_aggressive mood_electronic mood_happy mood_party mood_relaxed mood_sad rhythm tonal voice_instrumental
fetchart:
  enforce_ratio: yes
embedart:
  maxwidth: 1000
  remove_art_file: yes
lyrics:
  auto: no
  fallback: ' '
  sources: genius #default: google lyricwiki musixmatch genius
zero:
  fields: comments artist_sort albumartist_sort composer_sort
  update_database: true
replaygain:
  backend: gstreamer
edit:
  itemfields: title artist album voice_instrumental track lyrics 
  albumfields: album albumartist favorite 
missing:
  count: format
follow:
  email: leonardo.casamayor@gmail.com
  password: di#59pTqDKLh7%ou*iJG
  userid: do13euip7geu7jz4sbwgs6cabnckh8
  auto: yes
playlist:
    auto: yes
    playlist_dir: /home/leonardo/music/Library/Playlists
smartplaylist:
  playlist_dir: /home/leonardo/music/Library/Playlists
  playlists:
#mood playlists
    - name: 'Moods/Acoustic.m3u'
      query: 'mood_acoustic:0.95..1'
    - name: 'Moods/Aggressive.m3u'
      query: 'mood_aggressive:0.95..1'
    - name: 'Moods/Electronic.m3u'
      query: 'mood_electronic:0.95..1'
    - name: 'Moods/Happy.m3u'
      query: 'mood_happy:0.95..1'
    - name: 'Moods/Party.m3u'
      query: 'mood_party:0.95..1'
    - name: 'Moods/Relaxed.m3u'
      query: 'mood_relaxed:0.95..1'
    - name: 'Moods/Sad.m3u'
      query: 'mood_sad:0.95..1'
#voice/instrumental playlists
    - name: '$voice_instrumental.m3u'
      query: 'voice_instrumental::(voice|instrumental)'

item_fields:
    disc_and_track: u'%02i.%02i' % (disc, track) if
                    disctotal > 1 else u'%02i' % (track)
album_fields:
  albumduration: |
        total = 0
        for item in items:
            total += item.length
        return total


#Path config
paths:
  default: %asciify{%if{$favorite,Favorites,Artists}/%title{$albumartist}/%left{%title{$album},30}%aunique{}/%title{$albumartist} - %left{%title{$album},30}%aunique{} - $disc_and_track %left{%title{$title},30}}
  singleton: %asciify{%if{$favorite,Favorites,Singletons}/%title{$artist} - %left{%title{$title},30}}
  comp: %asciify{%if{$favorite,Favorites,Compilations}/%left{%title{$album},30}%aunique{}/$disc_and_track %left{%title{$title},30}}
  albumtype:single: %asciify{%if{$favorite,Favorites,Artists}/%title{$albumartist}/Singles/%left{%title{$album},30}%aunique{}/%title{$albumartist} - %left{%title{$album},30}%aunique{} - $disc_and_track %left{%title{$title},30}}
  albumtype:ep: %asciify{%if{$favorite,Favorites,Artists}/%title{$albumartist}/EPs/%left{%title{$album},30}%aunique{}/%title{$albumartist} - %left{%title{$album},30}%aunique{} - $disc_and_track %left{%title{$title},30}}
  albumtype:soundtrack: %asciify{%if{$favorite,Favourites,Soundtracks}/%left{%title{$album},30}%aunique{}/%left{%title{$album},30}%aunique - $disc_and_track %left{%title{$title},30}}
